services:
  # TODO: remove db, use RDS / Aurora
  db:
    image: postgres:alpine
    container_name: unaplauso-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - unaplauso-network
    volumes:
      - ./.db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']

  redis:
    image: redis:alpine
    container_name: unaplauso-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - unaplauso-network
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', '--raw', 'incr', 'ping']

  # TODO: API/web containers, :latest tag

volumes:
  db_data:

networks:
  unaplauso-network:
