services:
  # TODO: remove db, use RDS / Aurora
  db:
    image: postgres:alpine
    container_name: unaplauso-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - unaplauso-network
    volumes:
      - ./.db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']

  redis:
    image: redis:alpine
    container_name: unaplauso-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - unaplauso-network
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', '--raw', 'incr', 'ping']

  gateway:
    image: unaplauso/api-gateway:stable
    container_name: unaplauso-gateway
    restart: always
    env_file: ./.env
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'
    networks:
      - unaplauso-network
    depends_on:
      - db
      - redis
      # db:
      #   condition: service_healthy
      # redis:
      #   condition: service_healthy

  auth:
    image: unaplauso/api-auth:stable
    container_name: unaplauso-auth
    restart: always
    env_file: ./.env
    ports:
      - '${AUTH_PORT}:${AUTH_PORT}'
    networks:
      - unaplauso-network
    depends_on:
      - gateway

  audit:
    image: unaplauso/api-audit:stable
    container_name: unaplauso-audit
    restart: always
    env_file: ./.env
    networks:
      - unaplauso-network
    depends_on:
      - gateway

  file:
    image: unaplauso/api-file:stable
    container_name: unaplauso-file
    restart: always
    env_file: ./.env
    networks:
      - unaplauso-network
    depends_on:
      - gateway

  # web: # TODO: Hablar con Valen
  #   image: unaplauso/web:stable
  #  container_name: unaplauso-web
  #  restart: always
  #  env_file: ./.env
  #  ports:
  #    - '${WEB_PORT}:${WEB_PORT}'
  #  networks:
  #    - unaplauso-network
  #  depends_on:
  #    - gateway

volumes:
  db_data:

networks:
  unaplauso-network:
