x-defaults: &defaults
  env_file: ./.env
  restart: always
  depends_on:
    - gateway
  networks:
    - unaplauso-network

services:
  # TODO: remove db, use RDS / Aurora
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - unaplauso-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - unaplauso-network
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', '--raw', 'incr', 'ping']

  audit:
    <<: *defaults
    image: unaplauso/api-audit:stable

  auth:
    <<: *defaults
    image: unaplauso/api-auth:stable
    ports:
      - '${AUTH_PORT}:${AUTH_PORT}'

  event:
    <<: *defaults
    image: unaplauso/api-event:stable

  file:
    <<: *defaults
    image: unaplauso/api-file:stable

  gateway:
    <<: *defaults
    image: unaplauso/api-gateway:stable
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'
    depends_on:
      - db
      - redis

  moderation:
    <<: *defaults
    image: unaplauso/api-moderation:stable

  open:
    <<: *defaults
    image: unaplauso/api-open:stable

  payment:
    <<: *defaults
    image: unaplauso/api-payment:stable

  web:
    <<: *defaults
    image: unaplauso/web:stable
    ports:
      - '${WEB_PORT}:${WEB_PORT}'

networks:
  unaplauso-network:
