name: CI

on:
  push:
    branches:
      - stable
      - latest

env:
  SSH_HOST: ${{ contains(github.ref, 'stable') && secrets.SSH_PRODUCTION_HOST || secrets.SSH_TESTING_HOST }}

jobs:
  ci:
    # TODO: AÑADIR aws ecr get-login-password --region sa-east-1 | sudo \
      # docker login --username AWS --password-stdin 908027417939.dkr.ecr.sa-east-1.amazonaws.com
      
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          script: refresh-infra
          username: ec2-user
          host: ${{ env.SSH_HOST }}
          key: ${{ secrets.SSH_ROOT_KEY }}
