name: CICD

on:
  push:
    branches:
      - stable
      - latest

env:
  SSH_HOST: ${{ github.ref == 'refs/heads/stable' && '18.231.86.72' || secrets.SSH_TESTING_HOST }} # secrets.SSH_PRODUCTION_HOST

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          script: refresh-infra
          username: ec2-user
          host: ${{ env.SSH_HOST }}
          key: ${{ secrets.SSH_ROOT_KEY }}
