name: CICD

on:
  push:
    branches:
      - stable
      - latest

env:
  SSH_HOST: ${{ contains(github.ref, 'stable') && secrets.SSH_PRODUCTION_HOST || secrets.SSH_TESTING_HOST }}

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          script: refresh-infra
          username: ec2-user
          host: ${{ env.SSH_HOST }}
          key: ${{ secrets.SSH_ROOT_KEY }}
