name: Testing CICD

on:
  push:
    branches:
      - latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          script: refresh-infra
          username: ec2-user
          host: ${{ secrets.SSH_TESTING_HOST }}
          key: ${{ secrets.SSH_ROOT_KEY }}
